pipeline {
    agent {
        dockerfile {
            dir 'jenkins/multibranch'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node -v'
            }
        }
    }
}
