pipeline {
    agent {
        dockerfile {
            dir 'jenkins/multibranch'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git branch: 'main',
                url: 'https://github.com/gpremo-re/dummy-app.git'
            }
        }
        stage('Install Dependencies') {
            when { changeset 'frontend/package.json' }
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            when {
                anyOf {
                    changeset 'frontend/src/**'
                    changeset 'frontend/angular.json'
                    changeset 'tsconfig.app.json'
                    changeset 'tsconfig.json'
                }
            }
            steps {
                dir('frontend') {
                    sh 'npm run build -c=production'
                }
            }
            post {
                success {
                    archiveArtifacts 'frontend/.dist'
                }
            }
        }
    }
}
