pipeline {
    agent {
        dockerfile {
            dir 'jenkins/jobs/frontend'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git branch: 'main',
                url: 'https://github.com/gpremo-re/dummy-app.git'
            }
        }
        stage('Install Dependencies') {
            when {
                anyOf {
                    expression { currentBuild.previousCompletedBuild == null }
                    changeset 'frontend/package.json'
                }
            }
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
//             when {
//                 anyOf {
//                     expression { currentBuild.previousCompletedBuild == null }
//                     changeset 'frontend/src/**'
//                     changeset 'frontend/angular.json'
//                     changeset 'tsconfig.app.json'
//                     changeset 'tsconfig.json'
//                 }
//             }
            steps {
                dir('frontend') {
                    sh 'npx ng build -c=production'
                }
            }
        }
        stage('Reuse Previous Artifact') {
            when {
                expression {
                    dir('frontend/dist') { !findFiles().any() }
                }
            }
            steps {
                currentBuild.result = "SKIPPED"
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: 'frontend/dist/**'
        }
    }
}
