---
app:
    version: ${APP_VERSION}

logging:
    level:
        root: INFO
        org:
            springframework:
                web: DEBUG

server:
    servlet:
        session:
            cookie:
                same-site: "none"
                secure: true
