services:
    jenkins:
        build: .
        privileged: true
        user: root
        ports:
            - 9123:8080
            - 5000:5000
        env_file:
        -   .env
        container_name: jenkins
        volumes:
            - ./configuration:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
