services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 9123:8080
            - 5000:5000
        container_name: jenkins
        volumes:
            - ./configuration:/var/jenkins_home
            - /usr/local/bin/docker:/usr/bin/docker
