services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 9123:8080
            - 5000:5000
        container_name: jenkins
        volumes:
            - ./configuration:/var/jenkins_home
            - ./run/docker.sock:/var/run/docker.sock
